# 1. Base Image
FROM node:22-alpine AS base

# Install FFmpeg natively into the container
RUN apk add --no-cache ffmpeg

# 2. Dependencies
FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# 3. Builder
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1

# 👇 CRITICAL FIX: Declare ARGs in the builder stage where Next.js compiles the app
ARG NEXT_PUBLIC_BACKEND_API_URL
ARG NEXT_PUBLIC_SESSION_EXPIRY_SECONDS
ARG NEXT_PUBLIC_OTP_EXPIRY_SECONDS
ARG NEXT_PUBLIC_GET_DSPS_URL
ARG NEXT_PUBLIC_GET_DSPS_BASIC_AUTH_PASSWORD
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NEXT_PUBLIC_GOOGLE_CLIENT_SECRET

# 👇 CRITICAL FIX: Map the ARGs to ENVs so the "npm run build" process reads them
ENV NEXT_PUBLIC_BACKEND_API_URL=$NEXT_PUBLIC_BACKEND_API_URL
ENV NEXT_PUBLIC_SESSION_EXPIRY_SECONDS=$NEXT_PUBLIC_SESSION_EXPIRY_SECONDS
ENV NEXT_PUBLIC_OTP_EXPIRY_SECONDS=$NEXT_PUBLIC_OTP_EXPIRY_SECONDS
ENV NEXT_PUBLIC_GET_DSPS_URL=$NEXT_PUBLIC_GET_DSPS_URL
ENV NEXT_PUBLIC_GET_DSPS_BASIC_AUTH_PASSWORD=$NEXT_PUBLIC_GET_DSPS_BASIC_AUTH_PASSWORD
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID=$NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=$NEXT_PUBLIC_GOOGLE_CLIENT_SECRET

RUN npm run build

# 4. Runner
FROM base AS runner
WORKDIR /app


ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000
CMD ["npm", "start"]
