import { Props } from "../dashboard/salesReport/history/withdrawalLine";
import { LOCATION_TREE_ASSIGNOR, ROUTE_CONFIG } from "../type";

export const navigationLinks = [
  { name: "Home", link: "/" },
  { name: "Pricing", link: "/pricing" },
  { name: "Promotion", link: "/promotion" },
  { name: "Blog", link: "/blog" },
  { name: "Convert", link: "/convert" },
];

const nL = navigationLinks.map((n) => n.link);
export const rootScreenLinks = [...nL];

export const linkRoutes: ROUTE_CONFIG = {
  Home: "/",
  SignIn: "/login",
  SignUp: "/register",
  artists: {
    user: "/user/artists/create-artist",
    admin: "/admin/dashboard",
  },
};

export const USER_PORTAL_NAVIGATION_LINKS = {
  Artists: [
    { name: "create artists", link: `/user/artists/create-artist` },
    { name: "manage artists", link: `/user/artists/manage-artist` },
    { name: "artist's insight", link: `/user/artists/insight` },
  ],

  Songs: [
    { name: "upload songs", link: `/user/songs/upload-songs` },
    { name: "manage songs", link: `/user/songs/manage-songs` },
  ],

  Albums: [
    { name: "upload albums", link: `/user/songs/upload-albums` },
    { name: "manage albums", link: `/user/songs/manage-albums` },
  ],

  "": [
    { name: "sales report", link: `/user/sales/report` },
    { name: "promotions", link: `/user/promotions/` },
    { name: "advance", link: `/user/advance/` },
  ],
};

export const ADMIN_PORTAL_NAVIGATION_LINKS = {
  Artists: [
    { name: "create artists", link: `/user/artists/create-artist` },
    { name: "manage artists", link: `/user/artists/manage-artist` },
    { name: "artist's insight", link: `/user/artists/insight` },
  ],

  Songs: [
    { name: "upload songs", link: `/user/songs/upload-songs` },
    { name: "manage songs", link: `/user/songs/manage-songs` },
  ],

  Albums: [
    { name: "upload albums", link: `/user/songs/upload-albums` },
    { name: "manage albums", link: `/user/songs/manage-albums` },
  ],

  "": [
    { name: "sales report", link: `/user/sales/report` },
    { name: "promotions", link: `/user/promotions/` },
    { name: "advance", link: `/user/advance/` },
  ],
};

export const LOCATION_TREE: LOCATION_TREE_ASSIGNOR = {
  user: USER_PORTAL_NAVIGATION_LINKS,
  admin: ADMIN_PORTAL_NAVIGATION_LINKS,
};

export const portalScreens = [
  ...Object.values(USER_PORTAL_NAVIGATION_LINKS).flatMap((section) =>
    section.map((linkObj) => linkObj.link),
  ),
];
export const genreList = [
  "African",
  "Afro-Beat",
  "Afro-Pop",
  "Alternative",
  "Alternative/Experimental",
  " Alternative/Gothic",
  "Alternative/Grunge",
  " Alternative/Indie Pop",
  "Alternative/Indie Rock",
  "Alternative/Rock",
  " Ambient/New Age",
  "Ambient/New Age/Meditation",
  "Blues",
  "Blues/Contemporary Blues",
  "Blues/New Orleans Blues",
  "Blues/Traditional Blues",
  "Children’s Music",
  "Children’s Music/Classic",
  "Children’s Music/Holiday",
  "Children’s Music/Stories",
  "Classical",
  "Classical/Antique",
  "Classical/Baroque",
  " Classical/Chamber",
  "Classical/Concert",
  "Classical/Modern Compositions",
  "Classical/Opera",
  "Classical/Orchestral",
  "Classical/Piano",
  "Classical/Romantic",
  "Comedy",
  "Country",
  "Country/Bluegrass",
  "Country/Contemporary",
  "Country/Honky Tonk",
  "Country/Nashville",
  "Country/Pop",
  "Country/Square Dance",
  "Easy Listening",
  "Easy Listening/Bar Jazz/Cocktail",
  "Easy Listening/Bossa Nova",
  "Easy Listening/Lounge",
  "Easy Listening/Traditional",
  "Electronic",
  "Electronic/Acid House",
  "Electronic/Breaks",
  "Electronic/Broken beat",
  "Electronic/Chill Out",
  "Electronic/DJ Tools/Sample Packs",
  "Electronic/Dance",
  "Electronic/Deep House",
  "Electronic/Downtempo – experimental",
  "Electronic/Drum & Bass",
  "Electronic/Dub/Reggae/Dancehall",
  "Electronic/Dubstep/Grime",
  "Electronic/Electro House",
  "Electronic/Glitch Hop",
  "Electronic/Hard Dance",
  "Electronic/Hard Techno",
  "Electronic/Hardcore",
  "Electronic/Hardstyle",
  "Electronic/House",
  "Electronic/Indie Dance/Nu Disco",
  "Electronic/Jazz",
  "Electronic/Minimal",
  "Electronic/Pop Trance",
  "Electronic/Progressive House",
  "Electronic/Psy-Trance",
  "Electronic/Tech House",
  "Electronic/Techno",
  "Electronic/Trance",
  "Electronic/Trip Hop",
  "Experimental",
  "Fitness&Workout",
  "Flamenco",
  "Folk",
  "Funk/R&B",
  "Hip-Hop/Rap",
  "Hip-Hop/Rap/Gangsta & Hardcore",
  "Holiday/Christmas",
  "Inspirational",
  "Jazz",
  "Jazz/Bebop",
  "Jazz/Big Band",
  "Jazz/Brazilian Jazz",
  "Jazz/Classic",
  "Jazz/Contemporary",
  "Jazz/Dixie/Rag Time",
  "Jazz/Free Jazz",
  "Jazz/Fusion",
  "Jazz/Jazz Funk",
  "Jazz/Latin Jazz",
  "Jazz/Nu Jazz/Acid Jazz",
  "Jazz/Smooth Jazz",
  "Jazz/Swing",
  "Jazz/Traditional",
  "Jazz/World",
  "Karaoke",
  "Latin",
  "Latin/Bachata",
  "Latin/Banda",
  "Latin/Big Band",
  "Latin/Bolero",
  "Latin/Bossa Nova",
  "Latin/Brasil/Tropical",
  "Latin/Christian",
  "Latin/Conjunto",
  "Latin/Corridos",
  "Latin/Cuban",
  "Latin/Cumbia",
  "Latin/Duranguense",
  "Latin/Electronica",
  "Latin/Grupero",
  "Latin/Hip Hop",
  "Latin/Latin Rap",
  "Latin/Mambo",
  "Latin/Mariachi",
  "Latin/Norteño",
  "Latin/Pop",
  "Latin/Ranchera",
  "Latin/Reggaeton",
  "Latin/Regional Mexicano",
  "Latin/Rock en Español",
  " Latin/Salsa",
  "Latin/Salsa/Merengue",
  "Latin/Sierreño",
  "Latin/Sonidero",
  "Latin/Tango",
  "Latin/Tejano",
  "Latin/Tierra Caliente",
  "Latin/Traditional Mexican",
  "Latin/Vallenato",
  "New Age",
  "Pop",
  "Pop/Contemporary/Adult",
  "Pop/J-Pop",
  "Pop/K-Pop",
  "Pop/Mandopop",
  "Pop/Singer Songwriter",
  "Punk",
  "R&B",
  "Reggae",
  "Rock",
  "Rock/Brit-Pop",
  "Rock/Classic",
  "Rock/Glam Rock",
  " Rock/Hard Rock/Heavy Metal",
  "Rock/Heavy Metal",
  "Rock/Progressive",
  "Rock/Rock ‘n’ Roll",
  "Rock/Singer/Songwriter",
  "Ska",
  "Soul",
  "Soundtrack",
  "Soundtrack/Anime",
  "Soundtrack/Musical",
  "Soundtrack/TV",
  "Spiritual",
  "Spiritual/Christian",
  "Spiritual/Gospel",
  "Spiritual/Gregorian",
  "Spiritual/India",
  "Spiritual/Judaica",
  "Spiritual/World",
  "Spoken Word/Speeches",
  "Trap",
  "Trap/Future Bass",
  "Trap/Future Bass/Twerk",
  "Vocal/Nostalgia",
  "World",
  "World/African",
  "World/Afro-Beat",
  "World/Afro-Pop",
  "World/Americas/Argentina",
  "World/Americas/Brazilian",
  "World/Americas/Brazilian/Axé",
  "World/Americas/Brazilian/Black Music",
  "World/Americas/Brazilian/Bossa Nova",
  "World/Americas/Brazilian/Chorinho",
  "World/Americas/Brazilian/Folk",
  "World/Americas/Brazilian/Funk Carioca",
  "World/Americas/Brazilian/MPB",
  "World/Americas/Brazilian/Marchinha",
  "World/Americas/Brazilian/Pagode",
  "World/Americas/Brazilian/Samba",
  "World/Americas/Brazilian/Samba-Rock",
  "World/Americas/Brazilian/Samba-de-Raiz",
  "World/Americas/Brazilian/Samba-enredo",
  "World/Americas/Brazilian/Sambalanço",
  "World/Americas/Cajun-Creole",
  "World/Americas/Calypso",
  "World/Americas/Colombia",
  "World/Americas/Cuba-Caribbean",
  "World/Americas/Mexican",
  "World/Americas/North-American",
  "World/Americas/Panama",
  "World/Americas/Peru",
  "World/Americas/South-American",
  "World/Arabic",
  "World/Asian/Central Asia",
  "World/Asian/China",
  "World/Asian/India",
  "World/Asian/India-Bollywood",
  "World/Asian/Japan",
  "World/Asian/South Asia",
  "World/Australian/Pacific",
  "World/Ethnic",
  "World/Europe/Eastern",
  "World/Europe/French",
  "World/Europe/German",
  "World/Europe/Northern",
  "World/Europe/Southern",
  "World/Europe/Spain",
  "World/Europe/Western",
  "World/Mediterranean/Greece",
  "World/Mediterranean/Italy",
  "World/Mediterranean/Spain",
  "World/Russian",
  "World/Worldbeat",
];

export const territories = [
  { label: "Nigeria", value: "ng" },
  { label: "Ghana", value: "gh" },
  { label: "South Africa", value: "za" },
  { label: "Kenya", value: "ke" },
  { label: "USA", value: "us" },
  { label: "UK", value: "uk" },
];
export const performerRoles = [
  "Performer",
  "Soloist",
  "Choir",
  "Ensemble",
  "Orchestra",
  "Other Performer",
];
export const producerRoles = [
  "Performer",
  "Soloist",
  "Choir",
  "Ensemble",
  "Orchestra",
  "Other Performer",
];
export const country_list = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua &amp; Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad &amp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

// export const mockSongs:songFromApi[] = [
//   {
//     _id: "song1",
//     songTitle: "Alectric Dreams",
//     genre: "Electronic",
//     songLanguage: "English",
//     artistName: "Alex Rivera",
//     artist: {artistImage:"image", artistName: "Mia Lopez", createdAt: new Date("2026-01-23T23:00:00.000+00:00"),updatedAt:new Date("2026-01-23T23:00:00.000+00:00") }, // Assuming Artist has name and id
//     release_date: new Date("2026-01-23T23:00:00.000+00:00"),
//     preOrderDate: new Date("2026-01-23T23:00:00.000+00:00"),
//     featured_artist: [
//       { artistName: "Mia Lopez", spotifyId: "spotify_mia", appleId: "apple_mia" }
//     ],
//     performer: [
//       { name: "Alex Rivera", role: "Lead Vocals" },
//       { name: "Jordan Smith", role: "Guitar" }
//     ],
//     song_writer: [
//       { first_name: "Alex", last_name: "Rivera" },
//       { first_name: "Jordan", last_name: "Smith" }
//     ],
//     producer: [
//       { first_name: "Chris", last_name: "Johnson" }
//     ],
//     pre_order_check: true,
//     another_distribution_check: false,
//     territories: ["US", "UK", "Canada"],
//     song_audio: "https://example.com/audio/electric-dreams.mp3",
//     song_image: "https://soundmac1.s3.eu-north-1.amazonaws.com/testing/test_1767560802701/test_1767560802701.jpeg",
//     dsp: ["Spotify", "Apple Music", "YouTube Music"],
//     lyrics: "Verse 1: In the city lights...",
//     start_clip: "https://example.com/clip/electric-dreams.mp3",
//     isrc: "US-ABC-23-12345",
//     upc: "123456789012",
//     copyRightHolder: "Alex Rivera Music",
//     copyRightYear: "2023",
//     explicit_content: false,
//     createdAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     updatedAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     __v: 0,
//     songStatus: "draft"
//   },
//   {
//     _id: "song1",
//     songTitle: "Blectric Dreams",
//     genre: "Electronic",
//     songLanguage: "English",
//     artistName: "Alex Rivera",
//     artist: {artistImage:"image", artistName: "Mia Lopez", createdAt: new Date("2026-01-23T23:00:00.000+00:00"),updatedAt:new Date("2026-01-23T23:00:00.000+00:00") }, // Assuming Artist has name and id
//     release_date: new Date("2026-01-23T23:00:00.000+00:00"),
//     preOrderDate: new Date("2026-01-23T23:00:00.000+00:00"),
//     featured_artist: [
//       { artistName: "Mia Lopez", spotifyId: "spotify_mia", appleId: "apple_mia" }
//     ],
//     performer: [
//       { name: "Alex Rivera", role: "Lead Vocals" },
//       { name: "Jordan Smith", role: "Guitar" }
//     ],
//     song_writer: [
//       { first_name: "Alex", last_name: "Rivera" },
//       { first_name: "Jordan", last_name: "Smith" }
//     ],
//     producer: [
//       { first_name: "Chris", last_name: "Johnson" }
//     ],
//     pre_order_check: true,
//     another_distribution_check: false,
//     territories: ["US", "UK", "Canada"],
//     song_audio: "https://example.com/audio/electric-dreams.mp3",
//     song_image: "https://soundmac1.s3.eu-north-1.amazonaws.com/testing/test_1767560802701/test_1767560802701.jpeg",
//     dsp: ["Spotify", "Apple Music", "YouTube Music"],
//     lyrics: "Verse 1: In the city lights...",
//     start_clip: "https://example.com/clip/electric-dreams.mp3",
//     isrc: "US-ABC-23-12345",
//     upc: "123456789012",
//     copyRightHolder: "Alex Rivera Music",
//     copyRightYear: "2023",
//     explicit_content: false,
//     createdAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     updatedAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     __v: 0,
//     songStatus: "draft"
//   },
//   {
//     _id: "song1",
//     songTitle: "Clectric Dreams",
//     genre: "Electronic",
//     songLanguage: "English",
//     artistName: "Alex Rivera",
//     artist: {artistImage:"image", artistName: "Mia Lopez", createdAt: new Date("2026-01-23T23:00:00.000+00:00"),updatedAt:new Date("2026-01-23T23:00:00.000+00:00") }, // Assuming Artist has name and id
//     release_date: new Date("2026-01-23T23:00:00.000+00:00"),
//     preOrderDate: new Date("2026-01-23T23:00:00.000+00:00"),
//     featured_artist: [
//       { artistName: "Mia Lopez", spotifyId: "spotify_mia", appleId: "apple_mia" }
//     ],
//     performer: [
//       { name: "Alex Rivera", role: "Lead Vocals" },
//       { name: "Jordan Smith", role: "Guitar" }
//     ],
//     song_writer: [
//       { first_name: "Alex", last_name: "Rivera" },
//       { first_name: "Jordan", last_name: "Smith" }
//     ],
//     producer: [
//       { first_name: "Chris", last_name: "Johnson" }
//     ],
//     pre_order_check: true,
//     another_distribution_check: false,
//     territories: ["US", "UK", "Canada"],
//     song_audio: "https://example.com/audio/electric-dreams.mp3",
//     song_image: "https://soundmac1.s3.eu-north-1.amazonaws.com/testing/test_1767560802701/test_1767560802701.jpeg",
//     dsp: ["Spotify", "Apple Music", "YouTube Music"],
//     lyrics: "Verse 1: In the city lights...",
//     start_clip: "https://example.com/clip/electric-dreams.mp3",
//     isrc: "US-ABC-23-12345",
//     upc: "123456789012",
//     copyRightHolder: "Alex Rivera Music",
//     copyRightYear: "2023",
//     explicit_content: false,
//     createdAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     updatedAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     __v: 0,
//     songStatus: "draft"
//   },
//   {
//     _id: "song1",
//     songTitle: "Dlectric Dreams",
//     genre: "Electronic",
//     songLanguage: "English",
//     artistName: "Alex Rivera",
//     artist: {artistImage:"image", artistName: "Mia Lopez", createdAt: new Date("2026-01-23T23:00:00.000+00:00"),updatedAt:new Date("2026-01-23T23:00:00.000+00:00") }, // Assuming Artist has name and id
//     release_date: new Date("2026-01-23T23:00:00.000+00:00"),
//     preOrderDate: new Date("2026-01-23T23:00:00.000+00:00"),
//     featured_artist: [
//       { artistName: "Mia Lopez", spotifyId: "spotify_mia", appleId: "apple_mia" }
//     ],
//     performer: [
//       { name: "Alex Rivera", role: "Lead Vocals" },
//       { name: "Jordan Smith", role: "Guitar" }
//     ],
//     song_writer: [
//       { first_name: "Alex", last_name: "Rivera" },
//       { first_name: "Jordan", last_name: "Smith" }
//     ],
//     producer: [
//       { first_name: "Chris", last_name: "Johnson" }
//     ],
//     pre_order_check: true,
//     another_distribution_check: false,
//     territories: ["US", "UK", "Canada"],
//     song_audio: "https://example.com/audio/electric-dreams.mp3",
//     song_image: "https://soundmac1.s3.eu-north-1.amazonaws.com/testing/test_1767560802701/test_1767560802701.jpeg",
//     dsp: ["Spotify", "Apple Music", "YouTube Music"],
//     lyrics: "Verse 1: In the city lights...",
//     start_clip: "https://example.com/clip/electric-dreams.mp3",
//     isrc: "US-ABC-23-12345",
//     upc: "123456789012",
//     copyRightHolder: "Alex Rivera Music",
//     copyRightYear: "2023",
//     explicit_content: false,
//     createdAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     updatedAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     __v: 0,
//     songStatus: "draft"
//   },
//   {
//     _id: "song1",
//     songTitle: "Electric Dreams",
//     genre: "Electronic",
//     songLanguage: "English",
//     artistName: "Alex Rivera",
//     artist: {artistImage:"image", artistName: "Mia Lopez", createdAt: new Date("2026-01-23T23:00:00.000+00:00"),updatedAt:new Date("2026-01-23T23:00:00.000+00:00") }, // Assuming Artist has name and id
//     release_date: new Date("2026-01-23T23:00:00.000+00:00"),
//     preOrderDate: new Date("2026-01-23T23:00:00.000+00:00"),
//     featured_artist: [
//       { artistName: "Mia Lopez", spotifyId: "spotify_mia", appleId: "apple_mia" }
//     ],
//     performer: [
//       { name: "Alex Rivera", role: "Lead Vocals" },
//       { name: "Jordan Smith", role: "Guitar" }
//     ],
//     song_writer: [
//       { first_name: "Alex", last_name: "Rivera" },
//       { first_name: "Jordan", last_name: "Smith" }
//     ],
//     producer: [
//       { first_name: "Chris", last_name: "Johnson" }
//     ],
//     pre_order_check: true,
//     another_distribution_check: false,
//     territories: ["US", "UK", "Canada"],
//     song_audio: "https://example.com/audio/electric-dreams.mp3",
//     song_image: "https://soundmac1.s3.eu-north-1.amazonaws.com/testing/test_1767560802701/test_1767560802701.jpeg",
//     dsp: ["Spotify", "Apple Music", "YouTube Music"],
//     lyrics: "Verse 1: In the city lights...",
//     start_clip: "https://example.com/clip/electric-dreams.mp3",
//     isrc: "US-ABC-23-12345",
//     upc: "123456789012",
//     copyRightHolder: "Alex Rivera Music",
//     copyRightYear: "2023",
//     explicit_content: false,
//     createdAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     updatedAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     __v: 0,
//     songStatus: "draft"
//   },
//   {
//     _id: "song1",
//     songTitle: "Electric Dreams",
//     genre: "Electronic",
//     songLanguage: "English",
//     artistName: "Alex Rivera",
//     artist: {artistImage:"image", artistName: "Mia Lopez", createdAt: new Date("2026-01-23T23:00:00.000+00:00"),updatedAt:new Date("2026-01-23T23:00:00.000+00:00") }, // Assuming Artist has name and id
//     release_date: new Date("2026-01-23T23:00:00.000+00:00"),
//     preOrderDate: new Date("2026-01-23T23:00:00.000+00:00"),
//     featured_artist: [
//       { artistName: "Mia Lopez", spotifyId: "spotify_mia", appleId: "apple_mia" }
//     ],
//     performer: [
//       { name: "Alex Rivera", role: "Lead Vocals" },
//       { name: "Jordan Smith", role: "Guitar" }
//     ],
//     song_writer: [
//       { first_name: "Alex", last_name: "Rivera" },
//       { first_name: "Jordan", last_name: "Smith" }
//     ],
//     producer: [
//       { first_name: "Chris", last_name: "Johnson" }
//     ],
//     pre_order_check: true,
//     another_distribution_check: false,
//     territories: ["US", "UK", "Canada"],
//     song_audio: "https://example.com/audio/electric-dreams.mp3",
//     song_image: "https://soundmac1.s3.eu-north-1.amazonaws.com/testing/test_1767560802701/test_1767560802701.jpeg",
//     dsp: ["Spotify", "Apple Music", "YouTube Music"],
//     lyrics: "Verse 1: In the city lights...",
//     start_clip: "https://example.com/clip/electric-dreams.mp3",
//     isrc: "US-ABC-23-12345",
//     upc: "123456789012",
//     copyRightHolder: "Alex Rivera Music",
//     copyRightYear: "2023",
//     explicit_content: false,
//     createdAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     updatedAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     __v: 0,
//     songStatus: "draft"
//   },
//   {
//     _id: "song2",
//     songTitle: "Fidnight Serenade",
//     genre: "Jazz",
//     songLanguage: "Spanish",
//     artistName: "Sofia Martinez",
//     artist: {artistImage:"image", artistName: "Mia Lopez", createdAt: new Date("2026-01-23T23:00:00.000+00:00"),updatedAt:new Date("2026-01-23T23:00:00.000+00:00") }, // Assuming Artist has name and id
//     release_date: new Date("2026-01-23T23:00:00.000+00:00"),
//     preOrderDate: null,
//     featured_artist: [],
//     performer: [
//       { name: "Sofia Martinez", role: "Piano" },
//       { name: "Carlos Ruiz", role: "Saxophone" }
//     ],
//     song_writer: [
//       { first_name: "Sofia", last_name: "Martinez" }
//     ],
//     producer: [
//       { first_name: "Elena", last_name: "Gomez" }
//     ],
//     pre_order_check: false,
//     another_distribution_check: true,
//     territories: ["Spain", "Mexico", "Argentina"],
//     song_audio: "https://example.com/audio/midnight-serenade.mp3",
//     song_image: "https://soundmac1.s3.eu-north-1.amazonaws.com/testing/test_1767560802701/test_1767560802701.jpeg",
//     dsp: ["Spotify", "Deezer"],
//     lyrics: "Verso 1: Bajo la luna llena...",
//     start_clip: "https://example.com/clip/midnight-serenade.mp3",
//     isrc: "ES-XYZ-22-67890",
//     upc: "987654321098",
//     copyRightHolder: "Sofia Martinez Productions",
//     copyRightYear: "2022",
//     explicit_content: false,
//     createdAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     updatedAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     __v: 0,
//     songStatus: "pending"
//   },
//   {
//     _id: "song3",
//     songTitle: "Gock the Night",
//     genre: "Rock",
//     songLanguage: "English",
//     artistName: "The Thunderbolts",
//     artist: {artistImage:"image", artistName: "Mia Lopez", createdAt: new Date("2026-01-23T23:00:00.000+00:00"),updatedAt:new Date("2026-01-23T23:00:00.000+00:00") }, // Assuming Artist has name and id
//     release_date: new Date("2026-01-23T23:00:00.000+00:00"),
//     preOrderDate: new Date("2026-01-23T23:00:00.000+00:00"),
//     featured_artist: [
//       { artistName: "Jake Thompson", spotifyId: "spotify_jake", appleId: "apple_jake" },
//       { artistName: "Lisa Wong", spotifyId: "spotify_lisa", appleId: "apple_lisa" }
//     ],
//     performer: [
//       { name: "Mike Harris", role: "Drums" },
//       { name: "Jake Thompson", role: "Vocals" }
//     ],
//     song_writer: [
//       { first_name: "Mike", last_name: "Harris" },
//       { first_name: "Jake", last_name: "Thompson" }
//     ],
//     producer: [
//       { first_name: "Tom", last_name: "Anderson" }
//     ],
//     pre_order_check: true,
//     another_distribution_check: false,
//     territories: ["US", "UK", "Australia"],
//     song_audio: "https://example.com/audio/rock-the-night.mp3",
//     song_image: "https://soundmac1.s3.eu-north-1.amazonaws.com/testing/test_1767560802701/test_1767560802701.jpeg",
//     dsp: ["Spotify", "Apple Music", "Tidal"],
//     lyrics: "Verse 1: Lights are flashing...",
//     start_clip: "https://example.com/clip/rock-the-night.mp3",
//     isrc: "US-DEF-24-54321",
//     upc: "112233445566",
//     copyRightHolder: "Thunderbolts Records",
//     copyRightYear: "2024",
//     explicit_content: true,
//     createdAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     updatedAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     __v: 0,
//     songStatus: "approved"
//   },
//   {
//     _id: "song4",
//     songTitle: "Hcean Waves",
//     genre: "Ambient",
//     songLanguage: "Instrumental",
//     artistName: "Nature Sounds Collective",
//     artist: {artistImage:"image", artistName: "Mia Lopez", createdAt: new Date("2026-01-23T23:00:00.000+00:00"),updatedAt:new Date("2026-01-23T23:00:00.000+00:00") }, // Assuming Artist has name and id
//     release_date: new Date("2026-01-23T23:00:00.000+00:00"),
//     preOrderDate: null,
//     featured_artist: [],
//     performer: [
//       { name: "Anna Lee", role: "Synthesizer" }
//     ],
//     song_writer: [
//       { first_name: "Anna", last_name: "Lee" }
//     ],
//     producer: [
//       { first_name: "Ben", last_name: "Clark" }
//     ],
//     pre_order_check: false,
//     another_distribution_check: false,
//     territories: ["Global"],
//     song_audio: "https://example.com/audio/ocean-waves.mp3",
//     song_image: "https://soundmac1.s3.eu-north-1.amazonaws.com/testing/test_1767560802701/test_1767560802701.jpeg",
//     dsp: ["Spotify", "YouTube Music"],
//     lyrics: "", // Instrumental
//     start_clip: "https://example.com/clip/ocean-waves.mp3",
//     isrc: "GB-HIJ-23-98765",
//     upc: "556677889900",
//     copyRightHolder: "Nature Sounds Collective",
//     copyRightYear: "2023",
//     explicit_content: false,
//     createdAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     updatedAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     __v: 0,
//     songStatus: "pending"
//   },
//   {
//     _id: "song5",
//     songTitle: "Iance Fever",
//     genre: "Pop",
//     songLanguage: "English",
//     artistName: "Pop Starz",
//     artist: {artistImage:"image", artistName: "Mia Lopez", createdAt: new Date("2026-01-23T23:00:00.000+00:00"),updatedAt:new Date("2026-01-23T23:00:00.000+00:00") }, // Assuming Artist has name and id
//     release_date: new Date("2026-01-23T23:00:00.000+00:00"),
//     preOrderDate: new Date("2026-01-23T23:00:00.000+00:00"),
//     featured_artist: [
//       { artistName: "Remy Dubois", spotifyId: "spotify_remy", appleId: "apple_remy" }
//     ],
//     performer: [
//       { name: "Taylor Quinn", role: "Vocals" },
//       { name: "Remy Dubois", role: "Backing Vocals" }
//     ],
//     song_writer: [
//       { first_name: "Taylor", last_name: "Quinn" },
//       { first_name: "Remy", last_name: "Dubois" }
//     ],
//     producer: [
//       { first_name: "Sam", last_name: "Lee" }
//     ],
//     pre_order_check: true,
//     another_distribution_check: true,
//     territories: ["US", "France", "Japan"],
//     song_audio: "https://example.com/audio/dance-fever.mp3",
//     song_image: "https://soundmac1.s3.eu-north-1.amazonaws.com/testing/test_1767560802701/test_1767560802701.jpeg",
//     dsp: ["Spotify", "Apple Music", "TikTok"],
//     lyrics: "Verse 1: Feel the beat drop...",
//     start_clip: "https://example.com/clip/dance-fever.mp3",
//     isrc: "FR-KLM-24-11223",
//     upc: "778899001122",
//     copyRightHolder: "Pop Starz Entertainment",
//     copyRightYear: "2024",
//     explicit_content: false,
//     createdAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     updatedAt: new Date("2026-01-23T23:00:00.000+00:00"),
//     __v: 0,
//     songStatus: "rejected"
//   }
// ];
// utils/debounce.ts
// export function debounce<F extends (...args: any[]) => void>(func: F, delay: number) {
//   let timer: ReturnType<typeof setTimeout>;

//   return (...args: Parameters<F>) => {
//     if (timer) clearTimeout(timer);
//     timer = setTimeout(() => {
//       func(...args);
//     }, delay);
//   };
// }
// Retry configuration
export const RETRY_CONFIG = {
  maxAttempts: 3,
  initialDelayMs: 1000, // 1 second
  maxDelayMs: 10000, // 10 seconds
  backoffMultiplier: 2, // Exponential backoff
};
export const top_performing_artist = [
  {
    name: "Two-faced ban",
    featuredArtist: "feat Ariaate, Wenthy",
    amount: "9,432.00",
  },
  {
    name: "Stay a Little Longer",
    featuredArtist: "feat Ariaate, Wenthy",
    amount: "9,432.00",
  },
  {
    name: "Stay a Little Longer",
    featuredArtist: "feat Ariaate, Wenthy",
    amount: "9,432.00",
  },
];
export const withdrawalHistory: Props[] = [
  {
    account_number: "1234567890",
    status: "pending",
    amount: "9,432.00",
    date: "2026-01-19T10:23:01.128+00:00",
  },
  {
    account_number: "1234567890",
    status: "successful",
    amount: "9,432.00",
    date: "2026-01-19T10:23:01.128+00:00",
  },
  {
    account_number: "1234567890",
    status: "failed",
    amount: "9,432.00",
    date: "2026-01-19T10:23:01.128+00:00",
  },
];

export const nextReleases = [
  {
    releaseTitle: "Falling Skies",
    featuredArtist: ["feat Ariaate", "Wenthy"],
    artistName: "TomBaggz",
    releaseDate: "2026-01-19T10:23:01.128+00:00",
  },
  {
    releaseTitle: "Falling Skies",
    featuredArtist: ["feat Ariaate", "Wenthy"],
    artistName: "TomBaggz",
    releaseDate: "2026-01-19T10:23:01.128+00:00",
  },
  {
    releaseTitle: "Falling Skies",
    featuredArtist: ["feat Ariaate", "Wenthy"],
    artistName: "TomBaggz",
    releaseDate: "2026-01-19T10:23:01.128+00:00",
  },
  {
    releaseTitle: "Falling Skies",
    featuredArtist: ["feat Ariaate", "Wenthy"],
    artistName: "TomBaggz",
    releaseDate: "2026-01-19T10:23:01.128+00:00",
  },
];
export const requestReleaseMock = [
  {
    releaseTitle: "Falling Skies",
    featuredArtist: ["feat Ariaate", "Wenthy"],
    artistName: "TomBaggz",
    releaseDate: "2026-01-19T10:23:01.128+00:00",
  },
  {
    releaseTitle: "Falling Skies",
    featuredArtist: ["feat Ariaate", "Wenthy"],
    artistName: "TomBaggz",
    releaseDate: "2026-01-19T10:23:01.128+00:00",
  },
  {
    releaseTitle: "Falling Skies",
    featuredArtist: ["feat Ariaate", "Wenthy"],
    artistName: "TomBaggz",
    releaseDate: "2026-01-19T10:23:01.128+00:00",
  },
  {
    releaseTitle: "Falling Skies",
    featuredArtist: ["feat Ariaate", "Wenthy"],
    artistName: "TomBaggz",
    releaseDate: "2026-01-19T10:23:01.128+00:00",
  },
];
